In [1]:
import numpy as np

# Define the Hebbian learning rule
def hebbian_learning(inputs, outputs):
    """
    Calculate weight matrix using Hebbian learning.
    :param inputs: Input patterns (matrix)
    :param outputs: Output patterns (matrix)
    :return: Weight matrix
    """
    return np.dot(outputs.T, inputs)

# Define patterns
inputs = np.array([
    [1, -1, 1],  # Input pattern 1
    [-1, 1, -1], # Input pattern 2
    [1, 1, -1]   # Input pattern 3
])

outputs = np.array([
    [1, -1, 1],  # Output pattern 1
    [-1, 1, -1], # Output pattern 2
    [1, 1, -1]   # Output pattern 3
])

# Train using Hebbian rule
weights = hebbian_learning(inputs, outputs)
print("Weight Matrix:")
print(weights)

# Test the pattern matcher
def predict(input_pattern, weights):
    return np.sign(np.dot(weights, input_pattern))

test_pattern = np.array([1, -1, 1])  # Example test pattern
predicted_output = predict(test_pattern, weights)
print("\nTest Pattern:", test_pattern)
print("Predicted Output:", predicted_output)


Weight Matrix:
[[ 3 -1  1]
 [-1  3 -3]
 [ 1 -3  3]]

Test Pattern: [ 1 -1  1]
Predicted Output: [ 1 -1  1]
