# Associative memory using hebbrule

In [1]:
import numpy as np
import pandas as pd

# Define the binary patterns in a DataFrame
# Each row represents a binary pattern (e.g., 0 or 1)
data = {'Pattern1': [1, 0, 1, 0],
        'Pattern2': [0, 1, 0, 1],
        'Pattern3': [1, 1, 0, 0],
        'Pattern4': [0, 0, 1, 1]}

df = pd.DataFrame(data)
print("Original Data (Patterns):")
print(df)

# Convert the DataFrame to a numpy array (patterns as rows)
patterns = df.values.T  # Transpose to treat each pattern as a column

# Hebbian learning rule: W = X * X^T (Outer product of patterns)
def hebbian_learning(patterns):
    num_patterns = patterns.shape[1]
    num_neurons = patterns.shape[0]
    # Initialize weight matrix to zero
    weights = np.zeros((num_neurons, num_neurons))
    
    # Apply Hebbian learning rule
    for i in range(num_patterns):
        weights += np.outer(patterns[:, i], patterns[:, i])
    
    # Set diagonal elements to 0 (no self-feedback)
    np.fill_diagonal(weights, 0)
    
    return weights

# Train the associative memory using Hebbian learning
weights = hebbian_learning(patterns)

# Display the weight matrix after training
print("\nWeight Matrix (after Hebbian learning):")
print(weights)

# Function to retrieve the closest stored pattern
def retrieve_pattern(input_pattern, weights):
    # Apply the weight matrix to the input
    output_pattern = np.dot(weights, input_pattern)
    
    # Threshold the output to get binary values
    output_pattern = np.sign(output_pattern)
    
    return output_pattern

# Example: Retrieve a pattern for a noisy input
noisy_input = np.array([1, 0, 1, -1])  # Noisy version of Pattern1
print("\nNoisy Input:", noisy_input)

# Retrieve the closest pattern
retrieved_pattern = retrieve_pattern(noisy_input, weights)
print("\nRetrieved Pattern:", retrieved_pattern)


Original Data (Patterns):
   Pattern1  Pattern2  Pattern3  Pattern4
0         1         0         1         0
1         0         1         1         0
2         1         0         0         1
3         0         1         0         1

Weight Matrix (after Hebbian learning):
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

Noisy Input: [ 1  0  1 -1]

Retrieved Pattern: [0. 0. 1. 1.]


# Associative memory using outer product rule

In [2]:
import numpy as np
import pandas as pd

# Define the binary patterns in a DataFrame
data = {'Pattern1': [1, 0, 1, 0],
        'Pattern2': [0, 1, 0, 1],
        'Pattern3': [1, 1, 0, 0],
        'Pattern4': [0, 0, 1, 1]}

df = pd.DataFrame(data)
print("Original Data (Patterns):")
print(df)

# Convert the DataFrame to a numpy array (patterns as rows)
patterns = df.values.T  # Transpose to treat each pattern as a column

# Outer Product Rule: W = X * X^T (Outer product of patterns)
def outer_product_rule(patterns):
    num_patterns = patterns.shape[1]
    num_neurons = patterns.shape[0]
    
    # Initialize weight matrix to zero
    weights = np.zeros((num_neurons, num_neurons))
    
    # Apply the outer product rule to each pattern
    for i in range(num_patterns):
        weights += np.outer(patterns[:, i], patterns[:, i])  # Outer product of each pattern
    
    # Set diagonal elements to 0 (no self-feedback)
    np.fill_diagonal(weights, 0)
    
    return weights

# Train the associative memory using the outer product rule
weights = outer_product_rule(patterns)

# Display the weight matrix after training
print("\nWeight Matrix (after applying the Outer Product rule):")
print(weights)

# Function to retrieve the closest stored pattern
def retrieve_pattern(input_pattern, weights):
    # Apply the weight matrix to the input
    output_pattern = np.dot(weights, input_pattern)
    
    # Threshold the output to get binary values (sign function)
    output_pattern = np.sign(output_pattern)
    
    return output_pattern

# Example: Retrieve a pattern for a noisy input
noisy_input = np.array([1, 0, 1, -1])  # Noisy version of Pattern1
print("\nNoisy Input:", noisy_input)

# Retrieve the closest pattern
retrieved_pattern = retrieve_pattern(noisy_input, weights)
print("\nRetrieved Pattern:", retrieved_pattern)


Original Data (Patterns):
   Pattern1  Pattern2  Pattern3  Pattern4
0         1         0         1         0
1         0         1         1         0
2         1         0         0         1
3         0         1         0         1

Weight Matrix (after applying the Outer Product rule):
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

Noisy Input: [ 1  0  1 -1]

Retrieved Pattern: [0. 0. 1. 1.]
