# Bi directional Associative Memory (BAM) using hebbrule

In [3]:
import numpy as np

# Define the binary patterns for X and Y
X = np.array([[1, 0], [0, 1]])  # X represents input patterns (2x2 matrix)
Y = np.array([[1, 1], [0, 0]])  # Y represents output patterns (2x2 matrix)

# Display the original patterns
print("Original Input Patterns (X):")
print(X)

print("\nOriginal Output Patterns (Y):")
print(Y)

# Hebbian learning rule for Bi-directional Associative Memory
def hebbian_bam(X, Y):
    # Weight matrix from X to Y (W_xy)
    W_xy = np.dot(X.T, Y)
    
    # Weight matrix from Y to X (W_yx)
    W_yx = np.dot(Y.T, X)
    
    return W_xy, W_yx

# Train the BAM with the Hebbian rule
W_xy, W_yx = hebbian_bam(X, Y)

# Display the weight matrices
print("\nWeight Matrix from X to Y (W_xy):")
print(W_xy)

print("\nWeight Matrix from Y to X (W_yx):")
print(W_yx)

# Function to retrieve the pattern using the weight matrices
def retrieve_pattern(input_pattern, W):
    # Retrieve the associated pattern by multiplying input with the weight matrix
    output_pattern = np.dot(input_pattern, W)
    
    # Apply a threshold to convert continuous output to binary values (sign function)
    output_pattern = np.sign(output_pattern)
    
    return output_pattern

# Example: Retrieve the pattern from X to Y
input_X = np.array([1, 0])  # Input from X (first pattern)
retrieved_Y = retrieve_pattern(input_X, W_xy)

print("\nRetrieved Output Pattern from X to Y for input [1, 0]:")
print(retrieved_Y)

# Example: Retrieve the pattern from Y to X
input_Y = np.array([1, 1])  # Input from Y (first pattern)
retrieved_X = retrieve_pattern(input_Y, W_yx)

print("\nRetrieved Input Pattern from Y to X for input [1, 1]:")
print(retrieved_X)


Original Input Patterns (X):
[[1 0]
 [0 1]]

Original Output Patterns (Y):
[[1 1]
 [0 0]]

Weight Matrix from X to Y (W_xy):
[[1 1]
 [0 0]]

Weight Matrix from Y to X (W_yx):
[[1 0]
 [1 0]]

Retrieved Output Pattern from X to Y for input [1, 0]:
[1 1]

Retrieved Input Pattern from Y to X for input [1, 1]:
[1 0]


# Bi directional Associative Memory (BAM) using outer product rule

In [4]:
import numpy as np

# Define the binary patterns for X and Y
X = np.array([[1, 0], [0, 1]])  # Input patterns (2x2 matrix)
Y = np.array([[1, 1], [0, 0]])  # Output patterns (2x2 matrix)

# Display the original patterns
print("Original Input Patterns (X):")
print(X)

print("\nOriginal Output Patterns (Y):")
print(Y)

# Outer Product Rule for Bi-directional Associative Memory (BAM)
def outer_product_bam(X, Y):
    # Weight matrix from X to Y (W_xy)
    W_xy = np.outer(X[0], Y[0]) + np.outer(X[1], Y[1])  # Outer product sum for each pattern
    
    # Weight matrix from Y to X (W_yx)
    W_yx = np.outer(Y[0], X[0]) + np.outer(Y[1], X[1])  # Outer product sum for each pattern
    
    return W_xy, W_yx

# Train the BAM using the Outer Product rule
W_xy, W_yx = outer_product_bam(X, Y)

# Display the weight matrices
print("\nWeight Matrix from X to Y (W_xy):")
print(W_xy)

print("\nWeight Matrix from Y to X (W_yx):")
print(W_yx)

# Function to retrieve the pattern using the weight matrices
def retrieve_pattern(input_pattern, W):
    # Retrieve the associated pattern by multiplying input with the weight matrix
    output_pattern = np.dot(input_pattern, W)
    
    # Apply a threshold to convert continuous output to binary values (sign function)
    output_pattern = np.sign(output_pattern)
    
    return output_pattern

# Example: Retrieve the pattern from X to Y
input_X = np.array([1, 0])  # Input from X (first pattern)
retrieved_Y = retrieve_pattern(input_X, W_xy)

print("\nRetrieved Output Pattern from X to Y for input [1, 0]:")
print(retrieved_Y)

# Example: Retrieve the pattern from Y to X
input_Y = np.array([1, 1])  # Input from Y (first pattern)
retrieved_X = retrieve_pattern(input_Y, W_yx)

print("\nRetrieved Input Pattern from Y to X for input [1, 1]:")
print(retrieved_X)


Original Input Patterns (X):
[[1 0]
 [0 1]]

Original Output Patterns (Y):
[[1 1]
 [0 0]]

Weight Matrix from X to Y (W_xy):
[[1 1]
 [0 0]]

Weight Matrix from Y to X (W_yx):
[[1 0]
 [1 0]]

Retrieved Output Pattern from X to Y for input [1, 0]:
[1 1]

Retrieved Input Pattern from Y to X for input [1, 1]:
[1 0]


## Sir wala BAM

In [4]:
# Import Python Libraries
import numpy as np

# Take two sets of patterns:
# Set A: Input Pattern
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)
x3 = np.array([1, 1, -1, -1, 1, 1]).reshape(6, 1)
x4 = np.array([-1, -1, 1, 1, -1, -1]).reshape(6, 1)

# Set B: Target Pattern
y1 = np.array([1, 1, 1]).reshape(3, 1)
y2 = np.array([-1, -1, -1]).reshape(3, 1)
y3 = np.array([1, -1, 1]).reshape(3, 1)
y4 = np.array([-1, 1, -1]).reshape(3, 1)

# Calculate weight Matrix: W
inputSet = np.concatenate((x1, x2, x3, x4), axis = 1)
targetSet = np.concatenate((y1.T, y2.T, y3.T, y4.T), axis = 0)
print("\nWeight matrix:")
weight = np.dot(inputSet, targetSet)
print(weight)

print("\n------------------------------")

# Testing Phase
# Test for Input Patterns: Set A
print("\nTesting for input patterns: Set A")
def testInputs(x, weight):
    # Multiply the input pattern with the weight matrix
    # (weight.T X x)
    y = np.dot(weight.T, x)
    y[y < 0] = -1
    y[y >= 0] = 1
    return np.array(y)

print("\nOutput of input pattern 1") 
print(testInputs(x1, weight))
print("\nOutput of input pattern 2")
print(testInputs(x2, weight))
print("\nOutput of input pattern 3")
print(testInputs(x3, weight))
print("\nOutput of input pattern 4")
print(testInputs(x4, weight))

# Test for Target Patterns: Set B
print("\nTesting for target patterns: Set B")
def testTargets(y, weight):
    # Multiply the target pattern with the weight matrix
    # (weight X y)
    x = np.dot(weight, y)
    x[x <= 0] = -1
    x[x > 0] = 1
    return np.array(x)

print("\nInput of target pattern 1")
print(testTargets(y1, weight))
print("\nInput of target pattern 2")
print(testTargets(y2, weight))
print("\nInput of target pattern 3")
print(testTargets(y3, weight))
print("\nInput of target pattern 4")
print(testTargets(y4, weight))



Weight matrix:
[[4 0 4]
 [4 0 4]
 [0 4 0]
 [0 4 0]
 [4 0 4]
 [4 0 4]]

------------------------------

Testing for input patterns: Set A

Output of input pattern 1
[[1]
 [1]
 [1]]

Output of input pattern 2
[[-1]
 [-1]
 [-1]]

Output of input pattern 3
[[ 1]
 [-1]
 [ 1]]

Output of input pattern 4
[[-1]
 [ 1]
 [-1]]

Testing for target patterns: Set B

Input of target pattern 1
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Input of target pattern 2
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]

Input of target pattern 3
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]

Input of target pattern 4
[[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]
