# Self Organizing Map

In [ ]:
!pip install minisom

^C


Defaulting to user installation because normal site-packages is not writeable
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for minisom: filename=MiniSom-2.3.3-py3-none-any.whl size=11719 sha256=93f9cade587c36a6a3f38bc222aa5bb4e2bd46383c9800aedea15e0e48d23aef
  Stored in directory: c:\users\ahada\appdata\local\pip\cache\wheels\ec\7e\00\ac334ebb21e9016a73bef195e9732606217c6894f96bd51e6f
Successfully built minisom


In [5]:
import numpy as np
import pandas as pd
from minisom import MiniSom
import matplotlib.pyplot as plt

# Define the binary patterns (from your small dataframe)
data = {'Pattern1': [1, 0, 1, 0],
        'Pattern2': [0, 1, 0, 1],
        'Pattern3': [1, 1, 0, 0],
        'Pattern4': [0, 0, 1, 1]}

df = pd.DataFrame(data)
print("Original Data (Patterns):")
print(df)

# Convert the DataFrame to a numpy array (patterns as rows)
patterns = df.values.T  # Transpose to treat each pattern as a column

# Normalize the data (optional, but can help the SOM)
# This step scales the values to be between 0 and 1
patterns = (patterns - np.min(patterns, axis=1).reshape(-1, 1)) / (np.max(patterns, axis=1).reshape(-1, 1) - np.min(patterns, axis=1).reshape(-1, 1))

# Define the dimensions of the SOM (for example, a 3x3 grid)
som = MiniSom(x=3, y=3, input_len=patterns.shape[0], sigma=1.0, learning_rate=0.5)

# Train the SOM on the dataset
som.train(patterns, 100)  # 100 iterations for training

# Display the weights of the SOM
print("\nSOM Weights:")
print(som.get_weights())

Original Data (Patterns):
   Pattern1  Pattern2  Pattern3  Pattern4
0         1         0         1         0
1         0         1         1         0
2         1         0         0         1
3         0         1         0         1

SOM Weights:
[[[ 9.63180633e-01  6.06621652e-05  9.99932648e-01  3.67691245e-02]
  [ 7.46778425e-01  5.12871832e-03  9.10838415e-01  1.55800195e-01]
  [ 2.84248241e-01 -9.92523303e-02 -1.25723881e-01  6.23413847e-01]]

 [[ 3.71916403e-02  2.68313582e-03  9.97303284e-01  9.62807714e-01]
  [ 4.98233994e-01  4.91129681e-01  5.04008711e-01  4.99544385e-01]
  [ 1.85396466e-01  9.36034770e-01  5.99844097e-02  7.11626087e-01]]

 [[ 4.82797714e-01  4.73223080e-01  4.99330922e-01  4.94923681e-01]
  [ 9.64471596e-01  9.96716098e-01  3.26811680e-03  3.55217517e-02]
  [ 3.93682143e-02  9.99940881e-01  3.98435990e-05  9.60629713e-01]]]
