# Adaptive Resonance Theory (ART)

In [10]:
import numpy as np

class ART:
    def __init__(self, input_size, num_clusters, vigilance=0.5):
        self.weights = np.random.rand(num_clusters, input_size)  # Initialize weights randomly
        self.vigilance = vigilance
        self.num_clusters = num_clusters

    def normalize(self, pattern):
        return pattern / np.linalg.norm(pattern)

    def fit(self, patterns):
        for pattern in patterns.values():
            normalized_pattern = self.normalize(np.array(pattern))
            self._process_pattern(normalized_pattern)
            # Print the weights after each pattern is processed
            print("Weights after processing pattern {}:".format(pattern))
            print(self.weights)

    def _process_pattern(self, pattern):
        # Calculate the similarity between the input and the weights
        similarities = np.dot(self.weights, pattern)

        # Find the best matching unit (BMU)
        bmu_index = np.argmax(similarities)
        bmu_value = similarities[bmu_index]

        # Check if the BMU meets the vigilance criterion
        if bmu_value >= self.vigilance:
            # Update the weights of the BMU
            self.weights[bmu_index] += (pattern - self.weights[bmu_index]) * 0.1  # Learning rate
        else:
            # Check if there are available clusters
            if np.any(np.isnan(self.weights).any(axis=1)):
                # Find the first available cluster
                available_cluster = np.where(np.isnan(self.weights).any(axis=1))[0][0]
                self.weights[available_cluster] = pattern
            else:
                print("No available clusters. Pattern not assigned to any cluster.")

# Initialize ART with input size, number of clusters, and vigilance parameter
art = ART(input_size=4, num_clusters=3)

# Fit the model to the provided patterns
patterns = {
    'Pattern1': [0, 0, 0, 1],
    'Pattern2': [0, 1, 0, 1],
    'Pattern3': [0, 0, 1, 1],
    'Pattern4': [1, 0, 0, 0]
}
art.fit(patterns)

# Display the final weights
print("Final weights:")
print(art.weights)

Weights after processing pattern [0, 0, 0, 1]:
[[0.90129394 0.95029705 0.86988859 0.46648728]
 [0.38337086 0.23483211 0.6514186  0.78645763]
 [0.18191893 0.40992179 0.8056542  0.06656352]]
Weights after processing pattern [0, 1, 0, 1]:
[[0.81116455 0.92597803 0.78289973 0.49054923]
 [0.38337086 0.23483211 0.6514186  0.78645763]
 [0.18191893 0.40992179 0.8056542  0.06656352]]
Weights after processing pattern [0, 0, 1, 1]:
[[0.81116455 0.92597803 0.78289973 0.49054923]
 [0.34503377 0.2113489  0.65698742 0.77852255]
 [0.18191893 0.40992179 0.8056542  0.06656352]]
Weights after processing pattern [1, 0, 0, 0]:
[[0.83004809 0.83338022 0.70460976 0.4414943 ]
 [0.34503377 0.2113489  0.65698742 0.77852255]
 [0.18191893 0.40992179 0.8056542  0.06656352]]
Final weights:
[[0.83004809 0.83338022 0.70460976 0.4414943 ]
 [0.34503377 0.2113489  0.65698742 0.77852255]
 [0.18191893 0.40992179 0.8056542  0.06656352]]
